# Generated by Django 4.2.7 on 2025-07-10 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crops', '0002_systemsettings_systemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_crops',
            field=models.CharField(blank=True, help_text='Main crops you grow', max_length=200),
        ),
    ]
