# Generated by Django 5.2.4 on 2025-07-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_remove_diagnosis_prevention_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weatherlocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weatherlocation',
            name='api_provider',
            field=models.CharField(choices=[('openweathermap', 'OpenWeatherMap'), ('weatherapi', 'WeatherAPI.com'), ('accuweather', 'AccuWeather')], default='openweathermap', max_length=20),
        ),
        migrations.AddField(
            model_name='weatherlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='weatherlocation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='weatherlocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='weatherlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weatherlocation',
            name='longitude',
        ),
    ]
