# Generated by Django 4.2.7 on 2025-07-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_alter_weatherlocation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlocation',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherlocation',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
