# Generated by Django 4.2.7 on 2025-07-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_weatherlocation_latitude_weatherlocation_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weatherlocation',
            name='longitude',
        ),
    ]
